version: "3.9"

services:
  influxdb:
    image: influxdb:2.2
    ports:
      - "${INFLUXDB_PORT}:8086"

  service:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    ports:
      - "${SERVICE_PORT}:8080"