logging:
  config: "./logback.xml"
  file-name: "server"
  directory: "./logs"

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  writer-with-order-by-keys: true
  writer-with-default-pretty-printer: true

application:
  version: @project.version@ # read app version from maven property